-- SELECT 
-- artists.artist_name AS artista,
-- albuns.album_name AS album,
-- COUNT(following.artist_id) AS seguidores
-- FROM 
-- SpotifyClone.artists AS artist 
-- RIGHT JOIN 
-- SpotifyClone.albuns AS albuns ON artists.artist_id = albuns.artist_id 
-- INNER JOIN 
-- SpotifyClone.fo